#inheritance

#creating parent(base class)   todays lesson!
#creating child(derived class)
#using inherited methods
#adding new methods
#overwriting derived methods

class Person():#parent
    def __init__(self, first_name, last_name) :
        self.first_name = first_name
        self.last_name = last_name
        
    def hello(self):
        print("hello")

    def report(self):
        print(f"i am {self.first_name} {self.last_name}")

x = Person("John", "Smith")#instance of person
x.hello()
x.report()

#derived
class Agent(Person): #
#person instance on method Agent(instance) not Agent(Person()) so i have access to the methods!!

    #override report because we are an agent now hairy!
    def report(self):#overide by calling through agent ////////you can overide init too to add more inputs
        print("reporting for duty!!!")
        #return super().report()  ...this autogenerated
    def reveal(self,passcode):
        if passcode == 123:
            print("I am a secret agent")
        else:
            self.report()#person.report()
            


x = Agent("yanis","greayhead")
print(f"\nhello")

x.report()#it still works here even know you "unlock it on line 34."
#x.reveal(124)#without the key type error!! wrong number self.report()


x = Agent("Andy","yuuper")
print(f"\nhello")

x.reveal(123)
x.report()
